apiVersion: v1
kind: ServiceAccount
metadata:
  name: vespace-client-provisioner

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pvc-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: vespace-client-provisioner
  namespace: default
---
apiVersion: v1
kind: Pod 
metadata:
  name: vespace-provisioner
spec:
  containers:
  - command: 
    - /deploy/vespace-provisioner
    - --user=admin
    - --password=admin
    - --vespace=192.168.3.62:8081
    name: vespace-provisioner
    image: 192.168.18.250:5002/ufleet/vespace-provisioner:v1.0.3
  serviceAccount: vespace-client-provisioner
